export enum ConfigKeys {
  PORT_APP = 'PORT',
  APP_URL = 'APP_URL',
  USERNAME = 'USERNAME_DB',
  PASSWORD = 'PASSWORD',
  DATABASE = 'DATABASE',
  HOST = 'HOST_DB',
  PORT = 'PORT_DB',
  JWT_SECRET = 'JWT_SECRET',
}
